### ISSUE TITLE
How I can update hooks? 

### ISSUE THREAD

**Issue by Soliikaa** [iHelp101/XInsta#113]
Hi! I need help. I'd like to help to update hooks, but I don't know what are hooks. I haven't found any on Google about that. Any can make a simple tutorial, or explain a little? Thanks!

**Comment by lol7344** [comment]
Hooks are strings that change with every version of Instagram because they try to stop projects like this, making them unable to find the correct classes and methods to modify (hook to). They are literally the name of the classes and methods, but completely random generated.
So with a new version of IG, the same old class for "posts feed" has a different name (eg X.4nV, Z.3y7, etc).
You don't have to find them manually - you just need to install a supported Instagram version with Hooks that were already found by the developer. 
The order of things to do is:

1. Install XInsta and enable it in Xposed
2. Install a supported Instagram version (look at issue #111 )
3. open XInsta and update Hooks from GitHub
4. Reboot your phone

enjoy.
